# Digit Recognizer competition
> Author | Lavrov Evgeniy

## 1. Import Libraries & Load Data

In [1]:
import kagglehub
import pandas as pd
import xgboost as xgb
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

/home/koting/_code/Kaggle-Solutions/.venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## 2. Preparing dataframes

In [2]:
path = kagglehub.competition_download('digit-recognizer')
train_df = pd.read_csv(f"{path}/train.csv")
train_df.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
test_df = pd.read_csv(f"{path}/test.csv")
test_df.head()

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## 3. Training a model

In [4]:
X_train = train_df.drop('label', axis=1)
y_train = train_df['label']

X_train_part, X_val, y_train_part, y_val = train_test_split(
    X_train, y_train, test_size=0.2, random_state=42
)

model = RandomForestClassifier(random_state=42, n_estimators=200, max_depth=25)

model.fit(X_train_part, y_train_part)
final_preds_val = model.predict(X_val)
final_preds_train = model.predict(X_train_part)

## 4. Use of metrics to assess quality

In [5]:
precision = precision_score(y_val, final_preds_val, average='macro') 
recall = recall_score(y_val, final_preds_val, average='macro')
f1 = f1_score(y_val, final_preds_val, average='macro')

print(f"Validation accuracy: {accuracy_score(y_val, final_preds_val):.3f}")
print(f"Training accuracy: {accuracy_score(y_train_part, final_preds_train):.3f}")
print(f"Precision (macro): {precision:.3f}")
print(f"Recall (macro): {recall:.3f}")
print(f"F1-score (macro): {f1:.3f}")

Validation accuracy: 0.965
Training accuracy: 1.000
Precision (macro): 0.965
Recall (macro): 0.965
F1-score (macro): 0.965

## 5. Final predictions and csv

In [6]:
preds = model.predict(test_df)
submission = pd.DataFrame({'ImageId': range(1, len(preds)+1), 'Label': preds})
submission.to_csv('../submissions/digit-recognizer-submission.csv', index=False)
print(submission.head())

   ImageId  Label
0        1      2
1        2      0
2        3      9
3        4      9
4        5      3